# See http://www.appveyor.com/docs/appveyor-yml

version: '{build}'

image: Visual Studio 2017

# Branches to build
branches:
  only: 
    - master

configuration: 
  - Release 
  - Debug

environment:
  MSBUILD_FLAGS: /verbosity:minimal /maxcpucount /nologo /ds
  matrix: 
    # https://www.appveyor.com/docs/build-environment/#qt

    # MSVC x64
    - bitsize:    x64
      #qt:        latest\msvc2017_64
      qt:         5.11\msvc2017_64
      suffix:     msvc2017
      generator:  "Visual Studio 15 2017 Win64"

matrix:
  fast_finish: true

clone_depth: 5

# scripts that are called at very beginning, before repo cloning
init:
  # display eu-west time
  - tzutil /s "W. Europe Standard Time"
  - date /T & time /T
  # Set "build version number" to "short-commit-hash" or when tagged to "tag name" (Travis style)
  - ps: >-
      if ($env:APPVEYOR_REPO_TAG -eq "true")
      {
        Update-AppveyorBuild -Version "$env:APPVEYOR_REPO_TAG_NAME"
      }
      else
      {
        Update-AppveyorBuild -Version "dev-$($env:APPVEYOR_REPO_COMMIT.substring(0,7))"
      }

install:
  - cd %REPO_DIR%
  - git submodule update --init --recursive
  - git submodule status

before_build:  
  # set paths
  - set PATH=C:\Qt\%qt%\bin;C:\Qt\%qt%;%PATH%
  - set QTDIR=C:\Qt\%qt%
  # set vars
  - call "C:\Qt\%qt%\bin\qtenv2.bat"
  - call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvars64.bat"
  - set CPU=AMD64
  - set SPEC="win32-msvc"
  # show appveyor env vars
  - echo %CONFIGURATION%
  - echo %bitsize%
  - echo %generator%
  # show versions
  - msbuild /version
  - cmake --version
  - qmake -v
  # zlib
  - cd C:\projects\server-control-panel\third-party\zlib
  - mkdir build
  - cd build
  - cmake -G "%generator%" ../ -DCMAKE_INSTALL_PREFIX=../../../libs/zlib
  - msbuild %MSBUILD_FLAGS% /t:Build /p:Configuration=%CONFIGURATION% /p:Platform="%bitsize%" zlib.sln 
  - msbuild %MSBUILD_FLAGS% INSTALL.vcxproj
  # apply CMakeList patch for quazip
  - cd C:\projects\server-control-panel
  - copy third-party\patches\quazip\CMakeLists.txt third-party\quazip /Y
  - del C:\projects\server-control-panel\third-party\quazip\quazip.sln
  # quazip  
  - cd C:\projects\server-control-panel\third-party\quazip
  - mkdir build
  - cd build
  - if "%CONFIGURATION%"=="Release" ( set ZLIB_LIBRARY=C:\projects\server-control-panel\libs\zlib\lib\zlib.lib)
  - if "%CONFIGURATION%"=="Debug"   ( set ZLIB_LIBRARY=C:\projects\server-control-panel\libs\zlib\lib\zlibd.lib)
  - cmake -G "%generator%" -DCMAKE_INSTALL_PREFIX=../../../libs/quazip -DZLIB_INCLUDE_DIR="C:\projects\server-control-panel\libs\zlib\include" -DZLIB_LIBRARY="%ZLIB_LIBRARY%" ../
  - msbuild %MSBUILD_FLAGS% /maxcpucount:1 /t:Build /p:Configuration=%CONFIGURATION% /p:Platform="%bitsize%" quazip.sln
  - msbuild %MSBUILD_FLAGS% INSTALL.vcxproj
  # yaml-cpp
  - cd C:\projects\server-control-panel\third-party\yaml-cpp
  - mkdir build
  - cd build
  - cmake -G "%generator%" -DCMAKE_INSTALL_PREFIX=../../../libs/yaml-cpp ../ -DBUILD_SHARED_LIBS=OFF -DYAML_CPP_BUILD_TESTS=OFF -DYAML_CPP_BUILD_TOOLS=OFF -DYAML_CPP_BUILD_CONTRIB=OFF
  - msbuild %MSBUILD_FLAGS% /t:Build /p:Configuration=%CONFIGURATION% /p:Platform="%bitsize%" yaml_cpp.sln
  - msbuild %MSBUILD_FLAGS% INSTALL.vcxproj

build_script:
  - cd C:\projects\server-control-panel
  # versionize 
  - call bin\phing\phing.bat -f build.appveyor.xml
  # run qmake  
  - qmake wpnxm-servercontrolpanel.pro -r -spec %SPEC% -config %CONFIGURATION% 
  # run nmake on "Makefile.Release|Debug"
  - nmake /f Makefile.%CONFIGURATION% /NOLOGO

after_build:
  - echo %cd%
  - cd C:\projects\server-control-panel\%CONFIGURATION%
  - dir
  # identify and copy dependencies
  #- if "%CONFIGURATION%"=="Release" (
  #    windeployqt.exe --no-system-d3d-compiler --no-angle --no-opengl --no-opengl-sw --no-translations --release wpn-xm.exe
  #  )
  #- if "%CONFIGURATION%"=="Debug" (
  #    windeployqt.exe --no-system-d3d-compiler --no-angle --no-opengl --no-opengl-sw --no-translations --debug wpn-xm-debug.exe
  #  )
  # copy dependencies 
  # 1) zlib 
  - if "%CONFIGURATION%"=="Release" (
      copy C:\projects\server-control-panel\libs\zlib\bin\zlib.dll C:\projects\server-control-panel\%CONFIGURATION%\zlib.dll &&
      copy C:\projects\server-control-panel\third-party\zlib\build\%CONFIGURATION%\zlib.exp C:\projects\server-control-panel\libs\quazip\lib\zlib.exp
    )
  - if "%CONFIGURATION%"=="Debug" (
      copy C:\projects\server-control-panel\libs\zlib\bin\zlibd.dll C:\projects\server-control-panel\%CONFIGURATION%\zlibd.dll &&
      copy C:\projects\server-control-panel\third-party\zlib\build\%CONFIGURATION%\zlibd.exp C:\projects\server-control-panel\libs\quazip\lib\zlibd.exp
    )
  # 2) quazip
  - mkdir C:\projects\server-control-panel\libs\quazip\bin
  - if "%CONFIGURATION%"=="Release" (
      copy C:\projects\server-control-panel\libs\quazip\lib\quazip.dll C:\projects\server-control-panel\libs\quazip\bin\quazip.dll &&
      copy C:\projects\server-control-panel\libs\quazip\lib\quazip.dll C:\projects\server-control-panel\%CONFIGURATION%\quazip.dll &&
      copy C:\projects\server-control-panel\third-party\quazip\build\%CONFIGURATION%\quazip.exp C:\projects\server-control-panel\libs\quazip\lib\quazip.exp
    )
  - if "%CONFIGURATION%"=="Debug" (
      copy C:\projects\server-control-panel\libs\quazip\lib\quazipd.dll C:\projects\server-control-panel\libs\quazip\bin\quazipd.dll &&
      copy C:\projects\server-control-panel\libs\quazip\lib\quazipd.dll C:\projects\server-control-panel\%CONFIGURATION%\quazipd.dll &&
      copy C:\projects\server-control-panel\third-party\quazip\build\%CONFIGURATION%\quazipd.exp C:\projects\server-control-panel\libs\quazip\lib\quazipd.exp
    )
  # 3) yaml-cpp (statically linked)
  #- copy C:\projects\server-control-panel\libs\yaml-cpp\bin\yaml-cpp.dll C:\projects\server-control-panel\%CONFIGURATION%\yaml-cpp.dll
  # - no exports for yaml-cpp?
  # 4) openssl
  - mkdir C:\projects\server-control-panel\libs\openssl\bin
  # - C:\OpenSSL-Win64\bin
  - copy C:\OpenSSL-Win64\bin\libeay32.dll C:\projects\server-control-panel\libs\openssl\bin\libeay32.dll
  - copy C:\OpenSSL-Win64\bin\ssleay32.dll C:\projects\server-control-panel\libs\openssl\bin\ssleay32.dll
  - copy C:\OpenSSL-Win64\bin\libeay32.dll C:\projects\server-control-panel\%CONFIGURATION%\libeay32.dll
  - copy C:\OpenSSL-Win64\bin\ssleay32.dll C:\projects\server-control-panel\%CONFIGURATION%\ssleay32.dll
  # cleanups
  - del *.obj
  - del *.cpp
  - del vcredist*.exe 
  - del vc_redist*.exe 
  # - remove imagehandlers
  - del Qt5SVG.dll
  - del C:\projects\server-control-panel\%CONFIGURATION%\imageformats\qwebp.dll
  - del C:\projects\server-control-panel\%CONFIGURATION%\imageformats\qtiff.dll
  - del C:\projects\server-control-panel\%CONFIGURATION%\imageformats\qtga.dll
  - del C:\projects\server-control-panel\%CONFIGURATION%\imageformats\qgif.dll
  - del C:\projects\server-control-panel\%CONFIGURATION%\imageformats\qicns.dll
  - del C:\projects\server-control-panel\%CONFIGURATION%\imageformats\qsvg.dll  
  # package server control panel
  - 7z a -tzip wpnxm-scp-%APPVEYOR_BUILD_VERSION%-%bitsize%-%suffix%.zip . -mx9 -mmt
  - appveyor PushArtifact wpnxm-scp-%APPVEYOR_BUILD_VERSION%-%bitsize%-%suffix%.zip
  - del wpnxm-scp-%APPVEYOR_BUILD_VERSION%-%bitsize%-%suffix%.zip
  # package dependencies 
  - cd C:\projects\server-control-panel
  - 7z a -tzip wpnxm-dependencies-%APPVEYOR_BUILD_VERSION%-%bitsize%-%suffix%.zip libs -mx9 -mmt
  - appveyor PushArtifact wpnxm-dependencies-%APPVEYOR_BUILD_VERSION%-%bitsize%-%suffix%.zip
  # build enigma package
  - cd C:\projects\server-control-panel\bin
  - if "%CONFIGURATION%"=="Release" ( php\php EnigmaVirtualBox.php ..\release wpn-xm.exe wpn-xm_boxed.exe )
  - if "%CONFIGURATION%"=="Debug"   ( php\php EnigmaVirtualBox.php ..\debug wpn-xm-debug.exe wpn-xm_boxed.exe )
  - ren wpn-xm_boxed.exe wpn-xm.exe
  - 7z a -tzip wpnxm-scp-%APPVEYOR_BUILD_VERSION%-%bitsize%-%suffix%-boxed.zip wpn-xm.exe -mx9 -mmt
  - appveyor PushArtifact wpnxm-scp-%APPVEYOR_BUILD_VERSION%-%bitsize%-%suffix%-boxed.zip
  
test_script:
  # test normal executable
  - cd C:\projects\server-control-panel\%CONFIGURATION%
  - if "%CONFIGURATION%"=="Release" ( 
      wpn-xm.exe --help 
    )     
  - if "%CONFIGURATION%"=="Debug" ( 
      wpn-xm-debug.exe --help 
    )
  # test boxed executable
  - cd C:\projects\server-control-panel\bin
  - wpn-xm.exe --help

#artifacts:
#- path: build/scp-*.7z

#deploy:
#  provider: GitHub
#  auth_token:
#    secure: ---------------------
#  artifact: /.*\.7z/
#  on:
#    appveyor_repo_tag: true

# access build worker via remote desktop
on_finish:
  #- ps: if (($env:CONFIGURATION) -eq "Debug" ) { $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1')) }
  #- ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))