// File: "server-control-panel\src\app\version.h". 
// Generated by CMake from "server-control-panel\version.h.cmake"
//
// @ tokens @ are replaced during the build process.

#ifndef VERSION_H_
#define VERSION_H_

// Application version.
#define VERSION = @APP_VERSION_GITREV@ // 1.2.3+githash
#define APP_VERSION "@APP_VERSION_GITREV@" // "1.2.3+githash"
#define APP_VERSION_SHORT "@APP_VERSION@" // 1.2.3

// Application name
#define APP_NAME "WPN-XM Server Control Panel"
#define APP_NAME_AND_VERSION "WPN-XM Server Control Panel @APP_VERSION@"

// Settings for "application_win.rc".
// These values are the attributes of the executable, 
// shown when right-clicking on it.
#define VER_FILEVERSION @APP_VERSION_RC@
#define VER_FILEVERSION_STR "@APP_VERSION@\0"

#define VER_PRODUCTVERSION VER_FILEVERSION
#define VER_PRODUCTVERSION_STR VER_FILEVERSION_STR

#define VER_COMPANYNAME_STR "Koch Softwaresystemtechnik"
#define VER_COMPANYDOMAIN_STR "https://wpn-xm.org"
#define VER_FILEDESCRIPTION_STR "WPN-XM Server Control Panel"
#define VER_INTERNALNAME_STR "WPN-XM SCP"
#define VER_LEGALCOPYRIGHT_STR "Copyright (c) @YEAR@ Koch Softwaresystemtechnik"
#define VER_LEGALTRADEMARKS1_STR "All Rights Reserved"
#define VER_LEGALTRADEMARKS2_STR VER_LEGALTRADEMARKS1_STR
#define VER_ORIGINALFILENAME_STR "wpn-xm.exe"
#define VER_PRODUCTNAME_STR "WPN-XM Server Control Panel"

#endif /* VERSION_H_ */
